# 端口号
server:
  port: 8080

# 数据源
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/connsblog?characterEncoding=utf-8&useUnicode=true&serverTimezone=UTC
    username: root
    password: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    # druid数据源专有配置
  thymeleaf:
    cache: false
  # 文件上传
  servlet:
    multipart:
      # 开启multipart上传功能
      enabled: true
      # 上传文件总的最大值
      max-file-size: 10MB
      # 单个文件的最大值
      max-request-size: 10MB
mybatis:
  configuration:
    map-underscore-to-camel-case: true





